import os

DEBUG = True
SECRET_KEY = os.urandom(24)

DIALECT = 'mysql'
DRIVER = 'pymysql'
USERNAME = 'root'
PASSWORD = 'wsz970801'
LOCALHOST = 'localhost'
HOST = '127.0.0.1'
PORT = '3306'
DATABASE = 'db_web'

SQLALCHEMY_DATABASE_URI = "{}+{}://{}:{}@{}/{}?charset=utf8".format(
    DIALECT, DRIVER, USERNAME, PASSWORD, LOCALHOST, DATABASE
)

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
