"""empty message

Revision ID: 56907ee8ecfe
Revises: e89742e06b3c
Create Date: 2018-01-19 16:38:30.869324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56907ee8ecfe'
down_revision = 'e89742e06b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports_p',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.Integer(), nullable=False),
    sa.Column('report_time', sa.DateTime(), nullable=False),
    sa.Column('handle_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports_c',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comt_id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.Integer(), nullable=False),
    sa.Column('report_time', sa.DateTime(), nullable=False),
    sa.Column('handle_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comt_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports_c')
    op.drop_table('reports_p')
    # ### end Alembic commands ###
