"""empty message

Revision ID: 5ae21fd2f5b6
Revises: e6d7a6fb59af
Create Date: 2018-01-12 19:30:23.507983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ae21fd2f5b6'
down_revision = 'e6d7a6fb59af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('favor_num', sa.Integer(), nullable=False))
    op.drop_column('posts', 'read_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('read_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('posts', 'favor_num')
    op.drop_table('favorites')
    # ### end Alembic commands ###
