"""empty message

Revision ID: dae6047f6636
Revises: 50d1a4f5f2b8
Create Date: 2017-12-07 19:58:30.408864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae6047f6636'
down_revision = '50d1a4f5f2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('M', 'N', 'F'), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('recognition', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Enum('Y', 'N'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('pic', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
